version: "2"
services:
  moborec_node:
    image: node:6
    command: tail -f /dev/null
    volumes:
      - ./:/var/moborec/
    ports:
      - "8084:8084"

    extra_hosts:
      - "mongo:192.168.0.184"
      - "redis.tidido:192.168.0.184"